### ISSUE TITLE
Create Vending Machine FSM

### ISSUE THREAD

**Issue by alfadelta10010** [acmpesuecc/SystemVerilog-Playground#4]
**Design File:** 700 points

**Comment by tvs-tanmay** [comment]
can I be assigned to this

**Comment by alfadelta10010** [comment]
!assign @tvs-tanmay 45

**Comment by alfadelta10010** [comment]
@tvs-tanmay go ahead, you have 45 minutes

**Comment by alfadelta10010** [comment]
@tvs-tanmay go ahead, you have 45 mins

**Comment by tvs-tanmay** [comment]
just need a slight extension, just finished with dinner

**Comment by alfadelta10010** [comment]
!deassign @tvs-tanmay

**Comment by alfadelta10010** [comment]
!assign @tvs-tanmay 45

**Comment by alfadelta10010** [comment]
!deassign

**Comment by alfadelta10010** [comment]
!assign @tvs-tanmay 45

**Comment by alfadelta10010** [comment]
!assign @tvs-tanmay 45

**Comment by alfadelta10010** [comment]
!deassign

**Comment by rithulkamesh** [comment]
can I get assigned?

**Comment by alfadelta10010** [comment]
!assign @rithulkamesh 60

**Comment by alfadelta10010** [comment]
@rithulkamesh please work on Moore
